spring:
  profiles:
    active: dev
  application:
    name: avinecode
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=24h
    cache-names: languages

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true

yandex:
  api-key: ${YANDEX_API_KEY:}
  folder-id: ${YANDEX_FOLDER_ID:}

rsa:
  keys:
    private-key: ${RSA_PRIVATE_KEY:}
    public-key: ${RSA_PUBLIC_KEY:}
  token:
    expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access: DEBUG