---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: translatoruser
    password: 'translatoruser'
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  instancio:
    bean:
      validation:
        enabled: true
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
rsa:
  rsa-private-key: classpath:certs/private.pem
  rsa-public-key: classpath:certs/public.pem